version: "3.8"

services:
  app:
    build:
      context: .
    volumes:
      - .:/weheproject
    ports:
      - "8000:8000"
    image: app:weheproject
    container_name: weheproject_container
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: POSTGRES_DB
    ports:
      - "5432:5432"
